spring:
  datasource:
    url: jdbc:postgresql://db:5432/gis
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        show_sql: true

server:
  port: 8080